# This is a basic workflow to help you get started with Actions

name: "Autoupdate"

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ closed ]

    #types: [opened, synchronize, closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_ubuntu:
    name: Build (Ubuntu)
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: "> Check out current repository"
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          path: ${{ github.workspace }}

      - name: "> Check if PR was merged"
        id: check_merged
        run: |
          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            echo "PR was merged"
            echo "MERGED=true" >> $GITHUB_ENV
          else
            echo "PR was not merged"
            echo "MERGED=false" >> $GITHUB_ENV
          fi

      - name: "> Install Graphviz"
        uses: ts-graphviz/setup-graphviz@v1
        if: github.event_name == 'push' || env.MERGED == 'true'

      - name: "> Build graph"
        shell: bash
        env:
          target_file_path: ${{ github.workspace }}/scripts
        run: |
          echo "Workflow step executed from > $(pwd)";
          ls;
          find $(pwd) -type f -iname "*.sh" -exec chmod +x {} \;
          cd "./scripts/";
          echo "----------------------------------------";
          bash -e "./compile.sh";
        if: github.event_name == 'push' || env.MERGED == 'true'

      - name: "> Set up git user"
        if: github.event_name == 'push' || (env.MERGED == 'true')
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: "> Add changed files"
        if: github.event_name == 'push' || (env.MERGED == 'true')
        run: |
          git add .

      - name: "> Commit changes"
        if: github.event_name == 'push' || (env.MERGED == 'true')
        run: |
          git commit -m "Automated commit of changed files"
        continue-on-error: true

      - name: "> Push changes"
        if: github.event_name == 'push' || (env.MERGED == 'true')
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
